site_name: Plantilla para Documentación
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.keys
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
# Use the ReadTheDocs theme
theme:
  name: material
  highlightjs: true 
  palette:
      - scheme: default
        primary: red

  features:
    - content.code.copy
    - content.tooltips
extra_css:
  - https://use.fontawesome.com/releases/v6.5.2/css/all.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css

nav:
  - Inicio: index.md
  - Comandos: comandos.md
  - Ejemplo: ejemplo.md
  - Git: gitcmds.md
  - Primer Parcial:
      - Sesión 1: Primer_Parcial/sesion1.md
      - Electrónica:
          - Práctica 1: Primer_Parcial/Electronica/Práctica1.md
          - Práctica 2: Primer_Parcial/Electronica/Práctica2.md
          - Sesión 4: Primer_Parcial/Electronica/Práctica3.md

